ALTER SYSTEM SET processes=300 SCOPE=SPFILE;
ALTER SESSION SET CONTAINER=jbossts;

CREATE USER dtf11 IDENTIFIED BY dtf11;
GRANT CREATE SESSION, RESOURCE TO dtf11;
ALTER USER dtf11 QUOTA UNLIMITED ON USERS;

CREATE USER dtf12 IDENTIFIED BY dtf12;
GRANT CREATE SESSION, RESOURCE TO dtf12;
ALTER USER dtf12 QUOTA UNLIMITED ON USERS;
