# This GitHub Action workflow automatically adds labels to a pull request based on keywords found in its description.

name: Labeler

on:
  pull_request:
    types: [opened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Label PR based on axes in its description
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            if (!prBody) {
              core.info('PR body is empty. No labels to add.');
              return;
            }

            if (prBody.includes('NO_TEST')) {
              core.info('PR description contains NO_TEST. Skipping labeling.');
              return;
            }

            const labelMap = {
              'CORE': 'testing/core',
              'AS_TESTS': 'testing/as_tests',
              'RTS': 'testing/rts',
              'XTS': 'testing/xts',
              'QA_JTA': 'testing/qa_jta',
            };

            const labelsToAdd = [];

            // Replace "!<whitespace>" to "!" to treat "! CORE" as a single token "!CORE"
            const processedBody = prBody.replace(/!\s+/g, '!');
            
            // Normalize body: replace newlines/commas with spaces and split into a set of unique words (tokens)
            const tokens = new Set(processedBody.replace(/[\r\n,]/g, ' ').split(/\s+/));

            for (const [keyword, label] of Object.entries(labelMap)) {
              // A label is added if the keyword exists as a token AND its negated version ("!keyword") does not.
              if (tokens.has(keyword) && !tokens.has(`!${keyword}`)) {
                labelsToAdd.push(label);
              }
            }

            // If any labels need to be added, use the GitHub API to add them.
            if (labelsToAdd.length > 0) {
              core.info(`Adding labels: ${labelsToAdd.join(', ')}`);
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labelsToAdd,
              });
            } else {
              core.info('No labels added.');
            }
